spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaohe66_web?characterEncoding=UTF-8&amp;useUnicode=true&amp;autoReconnect=true
    username: root
    password: root

server:
  port: 8080

logging:
  file:
    path: /home/xiaohe/log/

xiaohe66:
  file:
    home: /home/xiaohe/file/
    maxMbChunkPer: 2
    maxMbFilePer: 64
  registerUrl: https://xiaohe66.com/sec/login/register/
