
debug: false
#--------------------------------------------
spring:
  profiles:
    active: dev
  aop.proxy-target-class: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#-------------------------------------------
server:
  port: 8080
  session:
    #用户会话session过期时间，以秒为单位
    timeout: 180
  tomcat:
    # 配置Tomcat编码,默认为UTF-8
    uri-encoding: UTF-8
    # 配置最大线程数
    max-threads: 1000
#------------- mybatis ---------------------------------
mybatis-plus:
  # 配置MyBaties全局配置文件:mybatis-config.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  # 对应实体类的包名
  type-aliases-package: com.xiaohe66.web.code
  # 和 typeAliasesPackage 配合使用，表示仅描述该类的子类
  type-aliases-super-type: com.xiaohe66.web.base.base.BasePo
  # mapper.xml文件所在位置
  mapper-locations: classpath:/mapper/**/*.xml

#------------- logback ---------------------------------
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: '%d{HH:mm:ss.SSS} %highlight[%-5p] [%thread] %cyan(%logger{15}) >>> %msg %n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%thread] %logger{30} >>> %msg %n'
  file:
    path: C:\\xiaohe66\\logs

#------------- shrio ---------------------------------


#配置性参数
xiaohe66:
  file:
    home: C:\\xiaohe66\\file
    maxMbChunkPer: 1
    maxMbFilePer: 50
  registerUrl: https://localhost/sec/login/register/
  wx:
    code2SessionUrl: http
    appId: appid
    appSecret: secret
