debug: true
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaohe66_web?characterEncoding=UTF-8&amp;useUnicode=true&amp;autoReconnect=true
    username: root
    password: root
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  file:
    path: C:\\xiaohe66\\log\\

xiaohe66:
  file:
    home: C:\\xiaohe66\\file\\
    maxMbChunkPer: 1
    maxMbFilePer: 8
  registerUrl: http://localhost/sec/login/register/
  wx:
    code2SessionUrl: http
    appId: appid
    appSecret: secret